# Generated by Django 6.0.4 on 2026-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('deploy_url', models.URLField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('in_progress', 'Em desenvolvimento'), ('paused', 'Pausado'), ('completed', 'Concluído')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
